name: build
on:
  push:
    branches: [ "main" ]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - '**'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
          sudo apt install -y valgrind
      - name: Set up Python PIP
        run: |
          python -m pip install --upgrade pip
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'
      - name: Install Conan
        run: |
          python -m pip install --upgrade "conan>=2.0,<3"
      - name: Setup Conan profile
        run: |
          conan profile detect --force
      - name: Configure project
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCONAN_BUILD_MISSING=ON
      - name: Build project
        run: |
          cmake --build build
      - name: Run unit tests
        run: |
          valgrind cmake --build build --target test
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python PIP
        run: |
          python -m pip install --upgrade pip
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'
      - name: Install Conan
        run: |
          python -m pip install --upgrade "conan>=2.0,<3"
      - name: Setup Conan profile
        run: |
          conan profile detect --force
      - name: Configure project
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCONAN_BUILD_MISSING=ON
      - name: Build project
        run: |
          .\build\conanrun.bat
          cmake --build build
      - name: Run unit tests
        run: |
          .\build\conanrun.bat
          cmake --build build --target run_tests
  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
    - uses: actions/checkout@v2
    - name: Zip conan recipe
      run: zip -r conan_recipe.zip conan_recipe/
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./conan_recipe.zip

